-- MySQL Script generated by MySQL Workbench
-- Sun May 18 12:58:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estado_logico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_logico` (
  `idestado_logico` INT NOT NULL,
  `descripción_estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado_logico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`propietario_mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`propietario_mascota` (
  `ID_propietario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `Celular` VARCHAR(15) NOT NULL,
  `Direccion` TEXT NOT NULL,
  `Correo_electronico` VARCHAR(100) NULL,
  `Fecha_registro` DATETIME NOT NULL,
  `estado_logico_idestado_logico` INT NOT NULL,
  PRIMARY KEY (`ID_propietario`, `estado_logico_idestado_logico`),
  INDEX `fk_propietario_mascota_estado_logico` (`estado_logico_idestado_logico` ASC),
  CONSTRAINT `fk_propietario_mascota_estado_logico`
    FOREIGN KEY (`estado_logico_idestado_logico`)
    REFERENCES `mydb`.`estado_logico` (`idestado_logico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especie` (
  `idespecie` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado_logico_idestado_logico` INT NOT NULL,
  PRIMARY KEY (`idespecie`, `estado_logico_idestado_logico`),
  INDEX `fk_Especie_estado_logico1` (`estado_logico_idestado_logico` ASC),
  CONSTRAINT `fk_Especie_estado_logico1`
    FOREIGN KEY (`estado_logico_idestado_logico`)
    REFERENCES `mydb`.`estado_logico` (`idestado_logico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Raza` (
  `idRaza` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Especie_idespecie` INT NOT NULL,
  `Especie_estado_logico_idestado_logico` INT NOT NULL,
  PRIMARY KEY (`idRaza`, `Especie_idespecie`, `Especie_estado_logico_idestado_logico`),
  INDEX `fk_Raza_Especie1` (`Especie_idespecie` ASC, `Especie_estado_logico_idestado_logico` ASC),
  CONSTRAINT `fk_Raza_Especie1`
    FOREIGN KEY (`Especie_idespecie`)
    REFERENCES `mydb`.`Especie` (`idespecie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartilla_vacunacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartilla_vacunacion` (
  `idCartilla_vacunacion` INT NOT NULL,
  `fecha_creacion` DATE NULL,
  PRIMARY KEY (`idCartilla_vacunacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mascota` (
  `idMascota` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha_nacimiento` DATE NOT NULL,
  `color` VARCHAR(45) NULL,
  `sexo` CHAR(1) NOT NULL,
  `caracteristicas_fisicas` TEXT NULL,
  `tamaño` VARCHAR(20) NULL,
  `peso` DECIMAL(5,2) NULL,
  `ID_propietario` INT NOT NULL,
  `idestado_logico` INT NOT NULL,
  `Raza_idRaza` INT NOT NULL,
  `Cartilla_vacunacion_idCartilla_vacunacion` INT NOT NULL,
  PRIMARY KEY (`idMascota`, `ID_propietario`, `idestado_logico`, `Raza_idRaza`, `Cartilla_vacunacion_idCartilla_vacunacion`),
  INDEX `fk_Mascota_propietario_mascota1` (`ID_propietario` ASC),
  INDEX `fk_Mascota_estado_logico1` (`idestado_logico` ASC),
  INDEX `fk_Mascota_Raza1` (`Raza_idRaza` ASC),
  INDEX `fk_Mascota_Cartilla_vacunacion1` (`Cartilla_vacunacion_idCartilla_vacunacion` ASC),
  CONSTRAINT `fk_Mascota_propietario_mascota1`
    FOREIGN KEY (`ID_propietario`)
    REFERENCES `mydb`.`propietario_mascota` (`ID_propietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mascota_estado_logico1`
    FOREIGN KEY (`idestado_logico`)
    REFERENCES `mydb`.`estado_logico` (`idestado_logico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mascota_Raza1`
    FOREIGN KEY (`Raza_idRaza`)
    REFERENCES `mydb`.`Raza` (`idRaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mascota_Cartilla_vacunacion1`
    FOREIGN KEY (`Cartilla_vacunacion_idCartilla_vacunacion`)
    REFERENCES `mydb`.`Cartilla_vacunacion` (`idCartilla_vacunacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vacunas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vacunas` (
  `idVacunas` INT NOT NULL,
  `Nombre_comercial` VARCHAR(45) NOT NULL,
  `codigo_vacuna` VARCHAR(45) NULL,
  `contraindicaciones` TEXT NULL,
  `advertencias` TEXT NULL,
  `efectos_secundarios` TEXT NULL,
  PRIMARY KEY (`idVacunas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_usuario` (
  `idTipo_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `DNI` INT NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `firma` TEXT NULL,
  `Tipo_usuario_idTipo_usuario` INT NOT NULL,
  `estado_logico_idestado_logico` INT NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`, `Tipo_usuario_idTipo_usuario`, `estado_logico_idestado_logico`),
  INDEX `fk_Usuario_Tipo_usuario1` (`Tipo_usuario_idTipo_usuario` ASC),
  INDEX `fk_Usuario_estado_logico1` (`estado_logico_idestado_logico` ASC),
  CONSTRAINT `fk_Usuario_Tipo_usuario1`
    FOREIGN KEY (`Tipo_usuario_idTipo_usuario`)
    REFERENCES `mydb`.`Tipo_usuario` (`idTipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_estado_logico1`
    FOREIGN KEY (`estado_logico_idestado_logico`)
    REFERENCES `mydb`.`estado_logico` (`idestado_logico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_consulta` (
  `idtipo_consulta` INT NOT NULL,
  `tipoc_onsulta` VARCHAR(45) NULL,
  `definicion_consulta` TEXT NULL,
  PRIMARY KEY (`idtipo_consulta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_cita` (
  `idEstado_cita` INT NOT NULL,
  `estado_cita` VARCHAR(20) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idEstado_cita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Metodo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Metodo_pago` (
  `idMetodo_pago` INT NOT NULL,
  `tipo_pago` VARCHAR(45) NULL,
  PRIMARY KEY (`idMetodo_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT,
  `fecha_cita` DATE NOT NULL,
  `hora_cita` TIME NOT NULL,
  `motivo` TEXT NOT NULL,
  `Mascota_idMascota` INT NOT NULL,
  `Usuario_Dni` INT NOT NULL,
  `Estado_cita_idEstado_cita` INT NOT NULL,
  `Metodo_pago_idMetodo_pago` INT NULL,
  `pagado` VARCHAR(2) NOT NULL COMMENT 'SI o NO',
  PRIMARY KEY (`idCita`, `Mascota_idMascota`, `Usuario_Dni`, `Estado_cita_idEstado_cita`, `Metodo_pago_idMetodo_pago`),
  INDEX `fk_Cita_Mascota1` (`Mascota_idMascota` ASC),
  INDEX `fk_Cita_Usuario1` (`Usuario_Dni` ASC),
  INDEX `fk_Cita_Estado_cita1` (`Estado_cita_idEstado_cita` ASC),
  INDEX `fk_Cita_Metodo_pago1` (`Metodo_pago_idMetodo_pago` ASC),
  CONSTRAINT `fk_Cita_Mascota1`
    FOREIGN KEY (`Mascota_idMascota`)
    REFERENCES `mydb`.`Mascota` (`idMascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Usuario1`
    FOREIGN KEY (`Usuario_Dni`)
    REFERENCES `mydb`.`Usuario` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Estado_cita1`
    FOREIGN KEY (`Estado_cita_idEstado_cita`)
    REFERENCES `mydb`.`Estado_cita` (`idEstado_cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Metodo_pago1`
    FOREIGN KEY (`Metodo_pago_idMetodo_pago`)
    REFERENCES `mydb`.`Metodo_pago` (`idMetodo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta` (
  `idConsulta` INT NOT NULL,
  `diagnostico` VARCHAR(45) NULL,
  `sintomas` TEXT NULL,
  `observaciones` TEXT NULL,
  `tratamiento` TEXT NULL,
  `Consultacol` VARCHAR(45) NULL,
  `tipo_consulta_idtipo_consulta` INT NOT NULL,
  `Cita_idCita` INT NOT NULL,
  PRIMARY KEY (`idConsulta`, `tipo_consulta_idtipo_consulta`, `Cita_idCita`),
  INDEX `fk_Consulta_tipo_consulta1` (`tipo_consulta_idtipo_consulta` ASC),
  INDEX `fk_Consulta_Cita1` (`Cita_idCita` ASC),
  CONSTRAINT `fk_Consulta_tipo_consulta1`
    FOREIGN KEY (`tipo_consulta_idtipo_consulta`)
    REFERENCES `mydb`.`tipo_consulta` (`idtipo_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Cita1`
    FOREIGN KEY (`Cita_idCita`)
    REFERENCES `mydb`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registro_Vacuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registro_Vacuna` (
  `idRegistro_Vacuna` INT NOT NULL AUTO_INCREMENT,
  `Fecha_administración` DATE NULL,
  `fecha_proxima_dosis` DATE NULL,
  `Cartilla_vacunacion_idCartilla_vacunacion` INT NOT NULL,
  `Vacunas_idVacunas` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Tipo_usuario_idTipo_usuario` INT NOT NULL,
  `Usuario_estado_logico_idestado_logico` INT NOT NULL,
  `Consulta_idConsulta` INT NULL,
  PRIMARY KEY (`idRegistro_Vacuna`, `Cartilla_vacunacion_idCartilla_vacunacion`, `Vacunas_idVacunas`, `Usuario_idUsuario`, `Usuario_Tipo_usuario_idTipo_usuario`, `Usuario_estado_logico_idestado_logico`, `Consulta_idConsulta`),
  INDEX `fk_Registro_Vacuna_Cartilla_vacunacion1` (`Cartilla_vacunacion_idCartilla_vacunacion` ASC),
  INDEX `fk_Registro_Vacuna_Vacunas1` (`Vacunas_idVacunas` ASC),
  INDEX `fk_Registro_Vacuna_Usuario1` (`Usuario_idUsuario` ASC, `Usuario_Tipo_usuario_idTipo_usuario` ASC, `Usuario_estado_logico_idestado_logico` ASC),
  INDEX `fk_Registro_Vacuna_Consulta1` (`Consulta_idConsulta` ASC),
  CONSTRAINT `fk_Registro_Vacuna_Cartilla_vacunacion1`
    FOREIGN KEY (`Cartilla_vacunacion_idCartilla_vacunacion`)
    REFERENCES `mydb`.`Cartilla_vacunacion` (`idCartilla_vacunacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Vacuna_Vacunas1`
    FOREIGN KEY (`Vacunas_idVacunas`)
    REFERENCES `mydb`.`Vacunas` (`idVacunas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Vacuna_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Tipo_usuario_idTipo_usuario` , `Usuario_estado_logico_idestado_logico`)
    REFERENCES `mydb`.`Usuario` (`DNI` , `Tipo_usuario_idTipo_usuario` , `estado_logico_idestado_logico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Vacuna_Consulta1`
    FOREIGN KEY (`Consulta_idConsulta`)
    REFERENCES `mydb`.`Consulta` (`idConsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_examen_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_examen_medico` (
  `idtipo_examen_medico` INT NOT NULL,
  `categoria_examen` VARCHAR(45) NOT NULL,
  `archivo_formato` BLOB NOT NULL,
  `laboratorio` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idtipo_examen_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_examen_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_examen_consulta` (
  `iddetalle_examen_consulta` INT NOT NULL,
  `examen_generado` TEXT NULL,
  `formato` VARCHAR(20) NULL,
  `fecha` DATE NULL,
  `tipo_examen_medico_idtipo_examen_medico` INT NOT NULL,
  `Consulta_idConsulta` INT NOT NULL,
  PRIMARY KEY (`iddetalle_examen_consulta`, `tipo_examen_medico_idtipo_examen_medico`, `Consulta_idConsulta`),
  INDEX `fk_detalle_examen_consulta_tipo_examen_medico1` (`tipo_examen_medico_idtipo_examen_medico` ASC),
  INDEX `fk_detalle_examen_consulta_Consulta1` (`Consulta_idConsulta` ASC),
  CONSTRAINT `fk_detalle_examen_consulta_tipo_examen_medico1`
    FOREIGN KEY (`tipo_examen_medico_idtipo_examen_medico`)
    REFERENCES `mydb`.`tipo_examen_medico` (`idtipo_examen_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_examen_consulta_Consulta1`
    FOREIGN KEY (`Consulta_idConsulta`)
    REFERENCES `mydb`.`Consulta` (`idConsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;